services:
  database:
    image: 'postgres:latest'
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: amrox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

